/**
 * Core type definitions for the Zero Agent Loop.
 */

export type Role = "system" | "user" | "assistant" | "tool";

export interface ToolCall {
  id: string;
  type: "function";
  function: {
    name: string;
    arguments: string; // JSON string of arguments
  };
}

export interface Message {
  role: Role;
  content: string | null;
  thought?: string; // Reasoning / thinking trace generated by the model
  name?: string;
  tool_call_id?: string;
  tool_calls?: ToolCall[];
}

export interface ToolParameterProperty {
  type: "string" | "number" | "boolean" | "object" | "array";
  description: string;
  enum?: string[];
  items?: { type: string };
}

export interface ToolParameters {
  type: "object";
  properties: Record<string, ToolParameterProperty>;
  required?: string[];
}

export interface Tool {
  name: string;
  description: string;
  parameters: ToolParameters;
  execute: (args: Record<string, any>) => Promise<string> | string;
}

export type ToolStatus = "success" | "tool_error";

export type OperationOutcome =
  | "success"
  | "failure"
  | "timeout"
  | "not_found"
  | "mismatch"
  | "invalid_target"
  | "tool_error";

export type ToolErrorType =
  | "tool_invocation_error"
  | "command_execution_error"
  | "filesystem_error"
  | "validation_error";

export interface ToolExecutionDetails {
  command: string;
  exitCode: number | null;
  stdout: string;
  stderr: string;
  durationMs: number;
  timedOut: boolean;
}

export interface ToolResponse<T = any> {
  toolStatus: ToolStatus;
  outcome: OperationOutcome;
  data?: T;
  execution?: ToolExecutionDetails;
  error?: {
    type: ToolErrorType;
    message: string;
    details?: string;
  };
  metadata?: Record<string, any>;
}

export interface ProviderConfig {
  name: string;
  baseURL: string;
  apiKey: string;
  model: string;
  defaultModels: string[];
  supportsReasoning?: boolean;
}

export interface TokenUsage {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
}

export interface LLMResponse {
  content: string | null;
  reasoning?: string | null;
  tool_calls?: ToolCall[];
  usage?: TokenUsage;
}

export type AgentEvent =
  | { type: "think:start" }
  | { type: "think:complete"; thought: string; durationMs: number }
  | { type: "tool:start"; toolName: string; args: Record<string, any>; callId: string }
  | {
      type: "tool:complete";
      toolName: string;
      args: Record<string, any>;
      result: string;
      durationMs: number;
      callId: string;
      parsed?: ToolResponse;
    }
  | { type: "response:start" }
  | { type: "response:complete"; content: string; durationMs: number; usage?: TokenUsage }
  | { type: "error"; message: string; phase: "think" | "tool" | "response" | "model" }
  | { type: "done"; finalResponse: string; history: Message[]; totalDurationMs: number };

export interface AgentResult {
  finalResponse: string;
  history: Message[];
  totalDurationMs: number;
  steps: number;
}

export interface SessionSnapshot {
  id: string;
  provider: ProviderConfig;
  systemPrompt: string;
  history: Message[];
  toolNames: string[];
  turnsCount?: number;
  createdAt?: string;
  updatedAt?: string;
}

export type TurnStep =
  | { type: "think"; thought: string; durationMs: number }
  | {
      type: "tool";
      toolName: string;
      args: Record<string, any>;
      callId: string;
      result: string;
      durationMs: number;
      status: "success" | "error";
      toolStatus?: ToolStatus;
      outcome?: OperationOutcome;
    }
  | { type: "response"; content: string; durationMs: number; usage?: TokenUsage }
  | { type: "error"; message: string; phase: "think" | "tool" | "response" | "model" };

export interface TurnRecord {
  turnIndex: number;
  sessionId: string;
  startedAt: string;
  completedAt?: string;
  userPrompt: string;
  status: "in_progress" | "success" | "error";
  steps: TurnStep[];
  error?: { message: string; phase: string };
  finalResponse?: string;
  totalDurationMs?: number;
}
